### ISSUE TITLE
测试用例参数化报错

### ISSUE THREAD

**Issue by beilu18** [zhaicao/HttpRunnerManager#4]
刚学httprunnermanager，有些不懂的地方，还请赐教，使用的是docker搭建的，
在用例管理-数据列表，添加接口参数化csv文件后，后面引用这个接口的文件时，报错了
![image](https://user-images.githubusercontent.com/40421326/79345373-9ebe8f80-7f63-11ea-9022-6fb2e1c23f4c.png)

有几下几点疑问：
1、${P(data/account.csv)}  函数引用的时候是否要指明路径和csv文件后缀
2、参数化后是在配置管理里面去引用，还是在单个用例里面去引用

**Comment by zhaicao** [comment]
不好意思，这块引用方法未说明
1. 函数引用的时候是否要指明路径和csv文件后缀
你是在页面引用，还是在自定义函数中引用？
页面引用：
![image](https://user-images.githubusercontent.com/25784134/87624760-1666ab00-c75b-11ea-8725-2dfc4125816d.png)
自定义函数引用的话，需要填写上传后的csv文件的实际物理地址(在容器中的实际物理地址)
数据页面展示的是名字，对应关系在数据库datainfo表中。需要指明容器内的路径和文件后缀(例：data/1554270583.csv)
2. 都可以，配置管理中是全局生效，单个用例是局部生效
